services:
  app:
    build: .
    image: arun0kb/pdf-editor-api:latest
    container_name: pdf-editor-api
    ports:
      - 3001:3001
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - LIMIT=${LIMIT}
      - HOST=${HOST}